version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - USE_REDIS=false
      - VIP_PATH=vip
      - MAL_CLIENT_ID=your_mal_client_id
      - KITSU_STREMIO_API_URL=https://anime-kitsu.strem.fun
      - PROXIFY_STREAMS=false
    volumes:
      - ./data:/app/data
    restart: unless-stopped
